version: "3.8"

services:
  bowled-redis:
    container_name: bowled-redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./deployment/volumes/redis:/data
    network_mode: host
