version: "3.8"

services:

  api-server:
    container_name: api-server
    build:
      context: ""
      dockerfile: ./deployment/rest_server/Dockerfile
    image: api-server:latest
    restart: unless-stopped
    ports:
      - 5000:5000

  redis-server:
    container_name: redis-server
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
